name: Docker Image CI 
 
on: 
  push: 
    branches: [ "main" ] 
  pull_request: 
    branches: [ "main" ] 

# Permisos necesarios para crear y publicar tags
permissions:
  contents: write
  packages: write
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
 
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0 
 
    - name: Set up Git 
      run: | 
        git config --global user.name "github-actions" 
        git config --global user.email "action@github.com" 
 
    - name: Determine Semantic Version 
      id: version 
      uses: PaulHatch/semantic-version@v4.0.3 
      with: 
        tag_prefix: "v" 
        # Simplificamos los patrones para mayor fiabilidad
        major_pattern: "BREAKING CHANGE"
        minor_pattern: "^feat:"
        patch_pattern: "^fix:|^docs:|^style:|^refactor:|^perf:|^test:|^chore:"
        format: "${major}.${minor}.${patch}" 
        search_commit_body: true
        bump_each_commit: true
        # Evitar que el versionado se rompa si no hay commits previos
        initial_version: "0.0.0"
 
    - name: Debug Version Info
      run: |
        echo "Previous Version: ${{ steps.version.outputs.previous_version }}"
        echo "New Version: ${{ steps.version.outputs.version }}"
        echo "Major: ${{ steps.version.outputs.major }}"
        echo "Minor: ${{ steps.version.outputs.minor }}"
        echo "Patch: ${{ steps.version.outputs.patch }}"
        echo "Last commit message: $(git log -1 --pretty=%B)"
 
    - name: Create Git Tag
      if: github.event_name != 'pull_request'
      run: |
        VERSION=${{ steps.version.outputs.version }}
        git tag v${VERSION}
        git push origin v${VERSION}
        echo "✅ Creado y publicado tag v${VERSION}"
 
    - name: Validate Docker Credentials 
      run: | 
        if [[ -z "${DOCKER_USER}" ]]; then 
          echo "❌ ERROR: DOCKER_USER is not set o vacío!" 
          exit 1 
        fi 
        if [[ -z "${DOCKER_PASSWORD}" ]]; then 
          echo "❌ ERROR: DOCKER_PASSWORD is not set o vacío!" 
          exit 1 
        fi 
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }} 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
 
    - name: Docker login 
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }} 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
      run: | 
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin 
        if [ $? -ne 0 ]; then 
          echo "❌ ERROR: Docker login fallido. Verifica tus credenciales." 
          exit 1 
        fi 
        echo "✅ Docker login exitoso!" 
 
    - name: Build Docker image 
      run: | 
        IMAGE_TAG=${{ steps.version.outputs.version }} 
        docker build -t jesmonsa/docker-graphql:${IMAGE_TAG} . 
        # También etiquetamos como latest
        docker build -t jesmonsa/docker-graphql:latest .
 
    - name: Push Docker image 
      run: | 
        IMAGE_TAG=${{ steps.version.outputs.version }} 
        docker push jesmonsa/docker-graphql:${IMAGE_TAG}
        docker push jesmonsa/docker-graphql:latest
 
    - name: Show Published Image Tag 
      run: | 
        IMAGE_TAG=${{ steps.version.outputs.version }} 
        echo "✅ Imagen publicada exitosamente: jesmonsa/docker-graphql:${IMAGE_TAG}"
        echo "✅ Imagen publicada exitosamente: jesmonsa/docker-graphql:latest"
