name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Debug Environment Variables
      run: |
        echo "DOCKER_USER is set: [${{ secrets.DOCKER_USER != '' }}]"
        echo "DOCKER_PASSWORD length: ${#DOCKER_PASSWORD}"
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Validate Docker Credentials
      run: |
        if [[ -z "${DOCKER_USER}" ]]; then
          echo "ERROR: DOCKER_USER is not set or empty!"
          exit 1
        fi
        if [[ -z "${DOCKER_PASSWORD}" ]]; then
          echo "ERROR: DOCKER_PASSWORD is not set or empty!"
          exit 1
        fi
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
        if [ $? -ne 0 ]; then
          echo "ERROR: Docker login failed. Check your credentials."
          exit 1
        fi
        echo "✅ Docker login successful!"

    - name: Build Docker image
      run: |
        docker build -t jesmonsa/docker-graphql:0.0.2 .

    - name: Push Docker image
      run: |
        docker push jesmonsa/docker-graphql:0.0.2
    
    
    
    
    
